language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: arkumawat78@gmail.com
    recipients:
      - aditya
    on_success: always
    on_failure: always
node_js:
  - "9"
git:
  depth: 3
script:
  - gatsby build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: ./public
  target-branch: main 
  on:
    branch: main
